{{- if and .Values.ember.requirepass (not .Values.ember.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ember.fullname" . }}-auth
  labels:
    {{- include "ember.labels" . | nindent 4 }}
type: Opaque
stringData:
  requirepass: {{ .Values.ember.requirepass | quote }}
{{- end }}
