//! Static command metadata table for the COMMAND command.
//!
//! Provides arity, flags, and key positions for every command ember supports.
//! Kept here so all command-describing data lives in one crate: enum variants,
//! attribute methods, and wire-protocol metadata are all in ember-protocol.
//! Adding a new command means editing this crate and one match arm in execute.rs.

use bytes::Bytes;

use crate::Frame;

/// Handles COMMAND [COUNT | INFO name... | DOCS name... | LIST].
///
/// Provides static command metadata for client library discovery.
/// The format matches Redis 7 conventions so clients can probe capabilities
/// without falling back to error-handling paths.
pub fn handle_command_cmd(subcommand: Option<&str>, args: &[String]) -> Frame {
    match subcommand {
        None | Some("LIST") => Frame::Array(COMMAND_TABLE.iter().map(command_entry).collect()),
        Some("COUNT") => Frame::Integer(COMMAND_TABLE.len() as i64),
        Some("INFO") => {
            if args.is_empty() {
                return Frame::Array(COMMAND_TABLE.iter().map(command_entry).collect());
            }
            let frames = args
                .iter()
                .map(|name| {
                    let upper = name.to_ascii_uppercase();
                    match COMMAND_TABLE.iter().find(|e| e.name == upper) {
                        Some(entry) => command_entry(entry),
                        None => Frame::Null,
                    }
                })
                .collect();
            Frame::Array(frames)
        }
        Some("DOCS") => {
            // return empty docs — clients use this for documentation display,
            // not capability detection. an empty map per command is valid.
            if args.is_empty() {
                return Frame::Array(vec![]);
            }
            let mut frames = Vec::with_capacity(args.len() * 2);
            for name in args {
                let upper = name.to_ascii_uppercase();
                frames.push(Frame::Bulk(Bytes::from(upper)));
                frames.push(Frame::Array(vec![]));
            }
            Frame::Array(frames)
        }
        Some("GETKEYS") => Frame::Array(vec![]),
        Some(other) => Frame::Error(format!("ERR unknown COMMAND subcommand '{other}'")),
    }
}

/// Builds a COMMAND entry array for a single command.
///
/// Format: [name, arity, [flags], first_key, last_key, step]
fn command_entry(e: &CommandEntry) -> Frame {
    Frame::Array(vec![
        Frame::Bulk(Bytes::from(e.name.to_ascii_lowercase())),
        Frame::Integer(e.arity),
        Frame::Array(e.flags.iter().map(|f| Frame::Simple((*f).into())).collect()),
        Frame::Integer(e.first_key),
        Frame::Integer(e.last_key),
        Frame::Integer(e.step),
    ])
}

struct CommandEntry {
    name: &'static str,
    arity: i64,
    flags: &'static [&'static str],
    first_key: i64,
    last_key: i64,
    step: i64,
}

/// Static command table. Arity: positive = exact, negative = minimum.
/// Flags: write, readonly, denyoom, admin, pubsub, noscript, fast, loading, etc.
static COMMAND_TABLE: &[CommandEntry] = &[
    CommandEntry {
        name: "ACL",
        arity: -2,
        flags: &["admin", "noscript", "loading"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandEntry {
        name: "APPEND",
        arity: 3,
        flags: &["write", "denyoom", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "AUTH",
        arity: -2,
        flags: &["noscript", "loading", "fast", "no_auth"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandEntry {
        name: "BGREWRITEAOF",
        arity: 1,
        flags: &["admin"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandEntry {
        name: "BGSAVE",
        arity: -1,
        flags: &["admin"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandEntry {
        name: "BITCOUNT",
        arity: -2,
        flags: &["readonly"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "BITOP",
        arity: -4,
        flags: &["write", "denyoom"],
        first_key: 2,
        last_key: -1,
        step: 1,
    },
    CommandEntry {
        name: "BITPOS",
        arity: -3,
        flags: &["readonly"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "BLPOP",
        arity: -3,
        flags: &["write", "noscript"],
        first_key: 1,
        last_key: -2,
        step: 1,
    },
    CommandEntry {
        name: "BRPOP",
        arity: -3,
        flags: &["write", "noscript"],
        first_key: 1,
        last_key: -2,
        step: 1,
    },
    CommandEntry {
        name: "CLIENT",
        arity: -2,
        flags: &["admin", "noscript", "loading", "fast"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandEntry {
        name: "CLUSTER",
        arity: -2,
        flags: &["admin"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandEntry {
        name: "COMMAND",
        arity: -1,
        flags: &["loading", "fast"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandEntry {
        name: "CONFIG",
        arity: -2,
        flags: &["admin", "loading", "noscript"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandEntry {
        name: "COPY",
        arity: -3,
        flags: &["write"],
        first_key: 1,
        last_key: 2,
        step: 1,
    },
    CommandEntry {
        name: "DBSIZE",
        arity: 1,
        flags: &["readonly", "fast"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandEntry {
        name: "DECR",
        arity: 2,
        flags: &["write", "denyoom", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "DECRBY",
        arity: 3,
        flags: &["write", "denyoom", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "DEL",
        arity: -2,
        flags: &["write"],
        first_key: 1,
        last_key: -1,
        step: 1,
    },
    CommandEntry {
        name: "DISCARD",
        arity: 1,
        flags: &["noscript", "loading", "fast"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandEntry {
        name: "ECHO",
        arity: 2,
        flags: &["fast"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandEntry {
        name: "EXEC",
        arity: 1,
        flags: &["noscript", "loading"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandEntry {
        name: "EXISTS",
        arity: -2,
        flags: &["readonly", "fast"],
        first_key: 1,
        last_key: -1,
        step: 1,
    },
    CommandEntry {
        name: "EXPIRE",
        arity: 3,
        flags: &["write", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "EXPIREAT",
        arity: 3,
        flags: &["write", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "EXPIRETIME",
        arity: 2,
        flags: &["readonly", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "FLUSHALL",
        arity: -1,
        flags: &["write"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandEntry {
        name: "FLUSHDB",
        arity: -1,
        flags: &["write"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandEntry {
        name: "GET",
        arity: 2,
        flags: &["readonly", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "GETBIT",
        arity: 3,
        flags: &["readonly", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "GETDEL",
        arity: 2,
        flags: &["write", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "GETEX",
        arity: -2,
        flags: &["write", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "GETRANGE",
        arity: 4,
        flags: &["readonly"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "GETSET",
        arity: 3,
        flags: &["write", "denyoom", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "HDEL",
        arity: -3,
        flags: &["write", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "HEXISTS",
        arity: 3,
        flags: &["readonly", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "HGET",
        arity: 3,
        flags: &["readonly", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "HGETALL",
        arity: 2,
        flags: &["readonly", "random"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "HINCRBY",
        arity: 4,
        flags: &["write", "denyoom", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "HINCRBYFLOAT",
        arity: 4,
        flags: &["write", "denyoom", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "HKEYS",
        arity: 2,
        flags: &["readonly", "sort_for_script"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "HLEN",
        arity: 2,
        flags: &["readonly", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "HMGET",
        arity: -3,
        flags: &["readonly", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "HMSET",
        arity: -4,
        flags: &["write", "denyoom", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "HRANDFIELD",
        arity: -2,
        flags: &["readonly", "random"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "HSCAN",
        arity: -3,
        flags: &["readonly", "random"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "HSET",
        arity: -4,
        flags: &["write", "denyoom", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "HVALS",
        arity: 2,
        flags: &["readonly", "sort_for_script"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "INCR",
        arity: 2,
        flags: &["write", "denyoom", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "INCRBY",
        arity: 3,
        flags: &["write", "denyoom", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "INCRBYFLOAT",
        arity: 3,
        flags: &["write", "denyoom", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "INFO",
        arity: -1,
        flags: &["loading", "fast"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandEntry {
        name: "KEYS",
        arity: 2,
        flags: &["readonly", "sort_for_script"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandEntry {
        name: "LASTSAVE",
        arity: 1,
        flags: &["random", "loading", "fast"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandEntry {
        name: "LINDEX",
        arity: 3,
        flags: &["readonly"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "LINSERT",
        arity: 5,
        flags: &["write", "denyoom"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "LLEN",
        arity: 2,
        flags: &["readonly", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "LMOVE",
        arity: 5,
        flags: &["write", "denyoom"],
        first_key: 1,
        last_key: 2,
        step: 1,
    },
    CommandEntry {
        name: "LMPOP",
        arity: -4,
        flags: &["write", "fast"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandEntry {
        name: "LPOS",
        arity: -3,
        flags: &["readonly"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "LPOP",
        arity: -2,
        flags: &["write", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "LPUSH",
        arity: -3,
        flags: &["write", "denyoom", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "LPUSHX",
        arity: -3,
        flags: &["write", "denyoom", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "LRANGE",
        arity: 4,
        flags: &["readonly"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "LREM",
        arity: 4,
        flags: &["write"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "LSET",
        arity: 4,
        flags: &["write", "denyoom"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "LTRIM",
        arity: 4,
        flags: &["write"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "MEMORY",
        arity: -2,
        flags: &["readonly"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandEntry {
        name: "MGET",
        arity: -2,
        flags: &["readonly", "fast"],
        first_key: 1,
        last_key: -1,
        step: 1,
    },
    CommandEntry {
        name: "MIGRATE",
        arity: -6,
        flags: &["write"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandEntry {
        name: "MONITOR",
        arity: 1,
        flags: &["admin", "loading"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandEntry {
        name: "MSET",
        arity: -3,
        flags: &["write", "denyoom"],
        first_key: 1,
        last_key: -1,
        step: 2,
    },
    CommandEntry {
        name: "MSETNX",
        arity: -3,
        flags: &["write", "denyoom"],
        first_key: 1,
        last_key: -1,
        step: 2,
    },
    CommandEntry {
        name: "MULTI",
        arity: 1,
        flags: &["noscript", "loading", "fast"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandEntry {
        name: "OBJECT",
        arity: -2,
        flags: &["slow"],
        first_key: 2,
        last_key: 2,
        step: 1,
    },
    CommandEntry {
        name: "PERSIST",
        arity: 2,
        flags: &["write", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "PEXPIRE",
        arity: 3,
        flags: &["write", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "PEXPIREAT",
        arity: 3,
        flags: &["write", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "PEXPIRETIME",
        arity: 2,
        flags: &["readonly", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "PING",
        arity: -1,
        flags: &["fast", "loading"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandEntry {
        name: "PSETEX",
        arity: 4,
        flags: &["write", "denyoom"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "PSUBSCRIBE",
        arity: -2,
        flags: &["pubsub", "loading", "fast"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandEntry {
        name: "PTTL",
        arity: 2,
        flags: &["readonly", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "PUBLISH",
        arity: 3,
        flags: &["pubsub", "fast"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandEntry {
        name: "PUBSUB",
        arity: -2,
        flags: &["pubsub", "random", "loading", "fast"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandEntry {
        name: "PUNSUBSCRIBE",
        arity: -1,
        flags: &["pubsub", "loading", "fast"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandEntry {
        name: "QUIT",
        arity: 1,
        flags: &["fast", "loading"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandEntry {
        name: "RANDOMKEY",
        arity: 1,
        flags: &["readonly", "random"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandEntry {
        name: "RENAME",
        arity: 3,
        flags: &["write"],
        first_key: 1,
        last_key: 2,
        step: 1,
    },
    CommandEntry {
        name: "ROLE",
        arity: 1,
        flags: &["noscript", "loading", "fast"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandEntry {
        name: "RPOP",
        arity: -2,
        flags: &["write", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "RPUSH",
        arity: -3,
        flags: &["write", "denyoom", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "RPUSHX",
        arity: -3,
        flags: &["write", "denyoom", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "SADD",
        arity: -3,
        flags: &["write", "denyoom", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "SCAN",
        arity: -2,
        flags: &["readonly"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandEntry {
        name: "SCARD",
        arity: 2,
        flags: &["readonly", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "SDIFF",
        arity: -2,
        flags: &["readonly", "sort_for_script"],
        first_key: 1,
        last_key: -1,
        step: 1,
    },
    CommandEntry {
        name: "SDIFFSTORE",
        arity: -3,
        flags: &["write", "denyoom"],
        first_key: 1,
        last_key: -1,
        step: 1,
    },
    CommandEntry {
        name: "SET",
        arity: -3,
        flags: &["write", "denyoom"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "SETBIT",
        arity: 4,
        flags: &["write", "denyoom"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "SETEX",
        arity: 4,
        flags: &["write", "denyoom"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "SETNX",
        arity: 3,
        flags: &["write", "denyoom", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "SETRANGE",
        arity: 4,
        flags: &["write", "denyoom"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "SINTER",
        arity: -2,
        flags: &["readonly", "sort_for_script"],
        first_key: 1,
        last_key: -1,
        step: 1,
    },
    CommandEntry {
        name: "SINTERCARD",
        arity: -3,
        flags: &["readonly"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandEntry {
        name: "SINTERSTORE",
        arity: -3,
        flags: &["write", "denyoom"],
        first_key: 1,
        last_key: -1,
        step: 1,
    },
    CommandEntry {
        name: "SISMEMBER",
        arity: 3,
        flags: &["readonly", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "SLOWLOG",
        arity: -2,
        flags: &["admin", "loading", "fast"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandEntry {
        name: "SMEMBERS",
        arity: 2,
        flags: &["readonly", "sort_for_script"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "SMISMEMBER",
        arity: -3,
        flags: &["readonly", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "SMOVE",
        arity: 4,
        flags: &["write", "fast"],
        first_key: 1,
        last_key: 2,
        step: 1,
    },
    CommandEntry {
        name: "SORT",
        arity: -2,
        flags: &["write", "denyoom"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "SPOP",
        arity: -2,
        flags: &["write", "random", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "SRANDMEMBER",
        arity: -2,
        flags: &["readonly", "random"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "SREM",
        arity: -3,
        flags: &["write", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "SSCAN",
        arity: -3,
        flags: &["readonly", "random"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "STRLEN",
        arity: 2,
        flags: &["readonly", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "SUBSCRIBE",
        arity: -2,
        flags: &["pubsub", "loading", "fast"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandEntry {
        name: "SUNION",
        arity: -2,
        flags: &["readonly", "sort_for_script"],
        first_key: 1,
        last_key: -1,
        step: 1,
    },
    CommandEntry {
        name: "SUNIONSTORE",
        arity: -3,
        flags: &["write", "denyoom"],
        first_key: 1,
        last_key: -1,
        step: 1,
    },
    CommandEntry {
        name: "TIME",
        arity: 1,
        flags: &["random", "loading", "fast"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandEntry {
        name: "TOUCH",
        arity: -2,
        flags: &["readonly", "fast"],
        first_key: 1,
        last_key: -1,
        step: 1,
    },
    CommandEntry {
        name: "TTL",
        arity: 2,
        flags: &["readonly", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "TYPE",
        arity: 2,
        flags: &["readonly", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "UNLINK",
        arity: -2,
        flags: &["write", "fast"],
        first_key: 1,
        last_key: -1,
        step: 1,
    },
    CommandEntry {
        name: "UNSUBSCRIBE",
        arity: -1,
        flags: &["pubsub", "loading", "fast"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandEntry {
        name: "UNWATCH",
        arity: 1,
        flags: &["noscript", "loading", "fast"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandEntry {
        name: "WAIT",
        arity: 3,
        flags: &["noscript"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandEntry {
        name: "WATCH",
        arity: -2,
        flags: &["noscript", "loading", "fast"],
        first_key: 1,
        last_key: -1,
        step: 1,
    },
    CommandEntry {
        name: "ZADD",
        arity: -4,
        flags: &["write", "denyoom", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "ZCARD",
        arity: 2,
        flags: &["readonly", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "ZCOUNT",
        arity: 4,
        flags: &["readonly", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "ZDIFF",
        arity: -3,
        flags: &["readonly", "sort_for_script"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandEntry {
        name: "ZDIFFSTORE",
        arity: -4,
        flags: &["write", "denyoom"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "ZINCRBY",
        arity: 4,
        flags: &["write", "denyoom", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "ZINTER",
        arity: -3,
        flags: &["readonly", "sort_for_script"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandEntry {
        name: "ZINTERSTORE",
        arity: -4,
        flags: &["write", "denyoom"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "ZLEXCOUNT",
        arity: 4,
        flags: &["readonly", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "ZMPOP",
        arity: -4,
        flags: &["write", "fast"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandEntry {
        name: "ZPOPMAX",
        arity: -2,
        flags: &["write", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "ZPOPMIN",
        arity: -2,
        flags: &["write", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "ZRANDMEMBER",
        arity: -2,
        flags: &["readonly", "random"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "ZRANGE",
        arity: -4,
        flags: &["readonly"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "ZRANGEBYSCORE",
        arity: -4,
        flags: &["readonly"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "ZRANK",
        arity: 3,
        flags: &["readonly", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "ZREM",
        arity: -3,
        flags: &["write", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "ZREVRANGE",
        arity: -4,
        flags: &["readonly"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "ZREVRANGEBYSCORE",
        arity: -4,
        flags: &["readonly"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "ZREVRANK",
        arity: 3,
        flags: &["readonly", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "ZSCAN",
        arity: -3,
        flags: &["readonly", "random"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "ZSCORE",
        arity: 3,
        flags: &["readonly", "fast"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
    CommandEntry {
        name: "ZUNION",
        arity: -3,
        flags: &["readonly", "sort_for_script"],
        first_key: 0,
        last_key: 0,
        step: 0,
    },
    CommandEntry {
        name: "ZUNIONSTORE",
        arity: -4,
        flags: &["write", "denyoom"],
        first_key: 1,
        last_key: 1,
        step: 1,
    },
];
